### ISSUE TITLE
Ensure display on Open Products Facts

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/folksonomy_frontend#1]
Ensure display on Open Products Facts.

- [x] The /keys page is working properly.
- [ ] The /product/* page is not working (first hypothesis was lack of nutrition section, but the issue is the same on Open Pet Food Facts)

**Comment by CharlesNepote** [comment]
A simple way to do it, without modifying perl front-end, is to move the "User properties" block (= the one dedicated to Folksonomy Engine) just before "Changes history" block -- but you would have to be connected to see it.

Another way is to display it after the following block: `<div itemscope="" itemtype="https://schema.org/Product">` (test to be done).
