### ISSUE TITLE
Allow to edit values

### ISSUE THREAD

**Issue by CharlesNepote** [openfoodfacts/folksonomy_frontend#3]
Add editValue() function.

**Comment by teolemon** [comment]
![image](https://user-images.githubusercontent.com/1689815/117824899-23670480-b26f-11eb-81bc-430f0ff1831d.png)
just for the readme. Please ignore this comment

**Comment by CharlesNepote** [comment]
Closed with 21494e25aea71f7fe3439d3d0cf9ebffd88a96b8.
