### ISSUE TITLE
Cannot set values when already logged: wrong bearer

### ISSUE THREAD

**Issue by stephanegigandet** [openfoodfacts/folksonomy_frontend#6]
I set a few properties, but it seems to work only when the script shows me a dialog box to log in.
When I try just after that to set another property, I get errors in the console, and it seems to have the wrong bearer: charlesnepote and not me.

When it does not work:

userscript.html?name=Folksonomy%20Engine%20user%20script.user.js&id=cb3b8300-226a-4b48-9a9f-d765bed8a83c:75 FEUS - Folksonomy Engine User Script - 2021-05-10T13:18 - mode: product view
userscript.html?name=Folksonomy%20Engine%20user%20script.user.js&id=cb3b8300-226a-4b48-9a9f-d765bed8a83c:80 authrenewal: 300000
userscript.html?name=Folksonomy%20Engine%20user%20script.user.js&id=cb3b8300-226a-4b48-9a9f-d765bed8a83c:138 FEUS - barcode: 5053827202787
jquery.js? [sm]:26 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ jquery.js? [sm]:26
userscript.html?name=Folksonomy%20Engine%20user%20script.user.js&id=cb3b8300-226a-4b48-9a9f-d765bed8a83c:227 FEUS - displayFolksonomyKeyValues() - No data
3userscript.html?name=Folksonomy%20Engine%20user%20script.user.js&id=cb3b8300-226a-4b48-9a9f-d765bed8a83c:212 k syntax is bad!
userscript.html?name=Folksonomy%20Engine%20user%20script.user.js&id=cb3b8300-226a-4b48-9a9f-d765bed8a83c:212 k syntax is bad!
userscript.html?name=Folksonomy%20Engine%20user%20script.user.js&id=cb3b8300-226a-4b48-9a9f-d765bed8a83c:612 FEUS - isWellLoggedIn - deadLine (1620904866918) - new Date().getTime() (1620904610777) = 256.141
userscript.html?name=Folksonomy%20Engine%20user%20script.user.js&id=cb3b8300-226a-4b48-9a9f-d765bed8a83c:619 FEUS - isWellLoggedIn() - true
userscript.html?name=Folksonomy%20Engine%20user%20script.user.js&id=cb3b8300-226a-4b48-9a9f-d765bed8a83c:360 FEUS - addKV() - bearer: charlesnepote__U3bc56413-5254-4530-b9bd-febb3fc46a6f
smacks-kellogg-s:1 Access to fetch at 'https://api.folksonomy.openfoodfacts.org/product' from origin 'https://fr.openfoodfacts.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
userscript.html?name=Folksonomy%20Engine%20user%20script.user.js&id=cb3b8300-226a-4b48-9a9f-d765bed8a83c:361 POST https://api.folksonomy.openfoodfacts.org/product net::ERR_FAILED
addKV @ userscript.html?name=Folksonomy%20Engine%20user%20script.user.js&id=cb3b8300-226a-4b48-9a9f-d765bed8a83c:361
newKV.onclick @ userscript.html?name=Folksonomy%20Engine%20user%20script.user.js&id=cb3b8300-226a-4b48-9a9f-d765bed8a83c:222
userscript.html?name=Folksonomy%20Engine%20user%20script.user.js&id=cb3b8300-226a-4b48-9a9f-d765bed8a83c:380 FEUS - addKV() - ERROR. Something went wrong:TypeError: Failed to fetch

When it works:

FEUS - Folksonomy Engine User Script - 2021-05-10T13:18 - mode: product view
userscript.html?name=Folksonomy%20Engine%20user%20script.user.js&id=cb3b8300-226a-4b48-9a9f-d765bed8a83c:80 authrenewal: 300000
userscript.html?name=Folksonomy%20Engine%20user%20script.user.js&id=cb3b8300-226a-4b48-9a9f-d765bed8a83c:138 FEUS - barcode: 3073781110180
jquery.js? [sm]:26 [Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience. For more help, check https://xhr.spec.whatwg.org/.
send @ jquery.js? [sm]:26
userscript.html?name=Folksonomy%20Engine%20user%20script.user.js&id=cb3b8300-226a-4b48-9a9f-d765bed8a83c:227 FEUS - displayFolksonomyKeyValues() - No data
userscript.html?name=Folksonomy%20Engine%20user%20script.user.js&id=cb3b8300-226a-4b48-9a9f-d765bed8a83c:212 k syntax is bad!
userscript.html?name=Folksonomy%20Engine%20user%20script.user.js&id=cb3b8300-226a-4b48-9a9f-d765bed8a83c:612 FEUS - isWellLoggedIn - deadLine (1620904466686) - new Date().getTime() (1620904554379) = -87.693
userscript.html?name=Folksonomy%20Engine%20user%20script.user.js&id=cb3b8300-226a-4b48-9a9f-d765bed8a83c:615 FEUS - isWellLoggedIn() - false ()
userscript.html?name=Folksonomy%20Engine%20user%20script.user.js&id=cb3b8300-226a-4b48-9a9f-d765bed8a83c:634 getConnectedUserID() > user_name: stephane
userscript.html?name=Folksonomy%20Engine%20user%20script.user.js&id=cb3b8300-226a-4b48-9a9f-d765bed8a83c:572 showPopupInfo(message) > [object Object]
userscript.html?name=Folksonomy%20Engine%20user%20script.user.js&id=cb3b8300-226a-4b48-9a9f-d765bed8a83c:634 getConnectedUserID() > user_name: stephane
userscript.html?name=Folksonomy%20Engine%20user%20script.user.js&id=cb3b8300-226a-4b48-9a9f-d765bed8a83c:525 <form name=​"login_form">​…​</form>​
[Violation] Forced reflow while executing JavaScript took 48ms
la-vache-qui-rit-bio-8-portions:1 [DOM] Input elements should have autocomplete attributes (suggested: "current-password"): (More info: https://goo.gl/9p2vKq) <input name=​"password" type=​"password" value>​
userscript.html?name=Folksonomy%20Engine%20user%20script.user.js&id=cb3b8300-226a-4b48-9a9f-d765bed8a83c:527 FEUS - Submited
userscript.html?name=Folksonomy%20Engine%20user%20script.user.js&id=cb3b8300-226a-4b48-9a9f-d765bed8a83c:531 FEUS - loginProcess - username: stephane - password: [my password]
userscript.html?name=Folksonomy%20Engine%20user%20script.user.js&id=cb3b8300-226a-4b48-9a9f-d765bed8a83c:543 FEUS - getCredentials - call https://api.folksonomy.openfoodfacts.org/auth
userscript.html?name=Folksonomy%20Engine%20user%20script.user.js&id=cb3b8300-226a-4b48-9a9f-d765bed8a83c:544 FEUS - getCredentials - username: stephane - password: [my password]
userscript.html?name=Folksonomy%20Engine%20user%20script.user.js&id=cb3b8300-226a-4b48-9a9f-d765bed8a83c:555 {access_token: "stephane__Ubff30e9c-e79c-44b7-b618-b63d1ae38464", token_type: "bearer"}
userscript.html?name=Folksonomy%20Engine%20user%20script.user.js&id=cb3b8300-226a-4b48-9a9f-d765bed8a83c:556 stephane__Ubff30e9c-e79c-44b7-b618-b63d1ae38464
userscript.html?name=Folksonomy%20Engine%20user%20script.user.js&id=cb3b8300-226a-4b48-9a9f-d765bed8a83c:558 FEUS - getCredentials - bearer: stephane__Ubff30e9c-e79c-44b7-b618-b63d1ae38464
userscript.html?name=Folksonomy%20Engine%20user%20script.user.js&id=cb3b8300-226a-4b48-9a9f-d765bed8a83c:612 FEUS - isWellLoggedIn - deadLine (1620904866918) - new Date().getTime() (1620904566918) = 300
userscript.html?name=Folksonomy%20Engine%20user%20script.user.js&id=cb3b8300-226a-4b48-9a9f-d765bed8a83c:619 FEUS - isWellLoggedIn() - true

**Comment by stephanegigandet** [comment]
Also I'd suggest to remove the password from the console log.

**Comment by CharlesNepote** [comment]
Closed with 21494e25aea71f7fe3439d3d0cf9ebffd88a96b8.
